### PR TITLE
Equivalent content in Maximums.txt to Maximums.nc

### PR DESCRIPTION
**Pull request by markwoodhouse**
Equivalent content in Maximums.txt to Maximums.nc
Removed MaxHeights, MaxSpeeds etc.
Amended documentation.
Additional tidy-up.

### CODE REVIEW

**Comment by jakelangham** [comment]
Have taken a look at this and run some tests. It seems to work right as far as I could easily tell. Happy to merge it today (pending response to below).

I like the new RunInfo.txt format. However, one thing I would say is that when extra info is added to the file as a comment string (e.g. deltaX), it makes it look an extra option, in the sense that one might expect to be able to uncomment it and change its value.

One alternative to consider would be adding all the 'extra stuff' at the top or bottom of the file in its own block. Perhaps with some brief explanatory comment. What do you think?

**Comment by markwoodhouse** [comment]
Good point. Moving to extra info is a good idea -- should I do that?

The reason for comment string is to avoid "not recognized" warning on read -- with this new format RunInfo.txt is a viable input file -- but maybe as a comment block at the end, this would be ok.

________________________________

**Comment by jakelangham** [comment]
I think it would be quickest for you to rejig the ordering - hopefully not a big job. Then I'll merge into main.

**Comment by markwoodhouse** [comment]
Will get on it!

**Comment by markwoodhouse** [comment]
Thanks Jake.

**Pull request merged**
